name: Achievements
main: com.nidefawl.Achievements.Achievements
author: nidefawl
version: 0.981
depend: [Stats]
commands:
    listachievements:
        description: Lists loaded achievements
        usage: /<command>
        aliases: listach
    achievements:
        description: Lists achievements you have
        usage: /<command>
        aliases: ach
    reloadachievements:
        description: Reloads achievements.txt
        usage: /<command>
        aliases: reloadach
    checkachievements:
        description: Checks outstanding achievements
        usage: /<command>
        aliases: checkach
    deleteachievements:
        description: Delete a players achievements
        usage: /<command> <player> [achievement-name] -f 
        aliases: delach
permissions:
    achievements.*:
        description: Gives access to all achiviements commands/features.
        children:
            achievements.check: true
            achievements.view.own: true
            achievements.view.list: true
    achievements.admin.*:
        description: Gives access to all achiviements admin commands.
        children:
            achievements.admin.check: true
            achievements.admin.reload: true
    achievements.check:
        description: only players that have that permissions will be checked + awarded
    achievements.view.own:
        description: grants access to /achievements (/ach)
    achievements.view.list:
        description: grants access to /listachievements (/listach)
    achievements.admin.check:
        description: grants access to /checkachievements (/chekcach)
    achievements.admin.reload:
        description: grants access to /reloadachievements (/reloadach)